apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: sample-secret
        image: nginx:latest
        name: sample-service
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
