apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# might be used with concept bases and overlays.
# bases:
# - ../base

# You can override the namespace
namespace: default

# list of resources to be applied
resources:
  - deployment.yaml
  - sealed-secrets/sealed-secret.yaml

# make sealed-secrets to use name of the secrets with hash value
configurations:
  - configuration/sealed-secret-config.yaml

# modifies behavior of all ConfigMap and Secret generators in the current kustomization.yaml
# may be used during initial generation of Secrets
# generatorOptions:
#   annotations:
#     sealedsecrets.bitnami.com/managed: "true"
#     sealedsecrets.bitnami.com/namespace-wide: "true"

# list of secrets
# generate empty secrets to provide hashed names for deployments
#secretGenerator:
 # - name: mysecret
  #  type: Opaque
    # might be used during initial generation of Secrets
    # env: secrets/sample-secret.txt
